### PR TITLE
server:core: remove redundant imports

### PR DESCRIPTION
**Pull request by cengizIO**

### CODE REVIEW

**Comment by cengizIO** [comment]
Funny. It compiles fine with 
```
rustc 1.36.0-nightly (963184bbb 2019-05-18)
```
hmm

**Comment by koute** [comment]
You mean locally? Perhaps you're not compiling everything locally that is compiled on Travis? Have you tried running `ci/run_tests.sh`? (It needs to be launched from the repository root.)

**Comment by cengizIO** [comment]
Silly me. I've removed two lines unwillingly. It should pass now.

Thanks!

**Comment by koute** [comment]
LGTM! Thanks!

**Pull request merged**
